spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      properties:
        sasl:
          mechanism: PLAIN
          #jaas:
          #  config: config
        security:
          protocol: PLAINTEXT
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: feed-fetcher
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

fetcher:
  rss-feed-providers:
    outages:
      url: ${OUTAGES_RSS_URL:http://localhost:8090}
      fetch-period: PT20S
      output-topic:
        name: outages
        partition: 3
        replication: 1

server:
  port: 8091
